name: Build

on:
  push:
    branches: [ master ]
#    tags:
#      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo in $GITHUB_WORKSPACE
      uses: actions/checkout@v2
    - name: Build and publish docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: flodocks/raincheck-notify
        username: flodocks
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        repository: flodocks/raincheck-notify
        tags: latest
